In [10]:
import numpy as np

In [11]:
N = 4
Mat=(np.random.random((N,N))*10.0)-5.0
print (Mat)

print(Mat[np.shape(Mat)[0]-1,:])

[[-2.65532106 -2.46678627 -3.59021917 -3.19558452]
 [ 0.206027   -2.97492573  4.49923527  1.62720719]
 [-2.14404271 -3.6475364  -3.68802114  3.28708437]
 [-1.75030901  1.08429891  1.49238163 -2.21634131]]
[-1.75030901  1.08429891  1.49238163 -2.21634131]


In [12]:
filas=np.shape(Mat)[0]
columnas=np.shape(Mat)[1]

for i in range(filas):
    for j in range(columnas):
        if (Mat[i,j] == 2):
            print (Mat[i][j])
            print(Mat[i][:])
        
        